name: Release

on:
  push:
    tags:
    - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: ${{ github.ref_name }}

jobs:
  release-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, darwin ]
        goarch: [ 386, arm64, amd64 ]
        exclude:
        - goarch: "386"
          goos: darwin
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x
    - name: Checkout the latest code
      uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build ${{ matrix.goos }}/${{ matrix.goarch }}
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      shell: bash
      run: |
        make build-release          \
          && mkdir dist             \
          && mv my_bin dist/my_bin  \
          && tar -czvf my_bin-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz -C dist/ .

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: my_bin-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz

  release-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker build & push
      uses: docker/build-push-action@v3
      with:
        push: true
        context: .
        file: ./Dockerfile-release
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        build-args: |
          VERSION=${{ github.ref_name }}
        tags: |
          jsfpdn/my_bin:${{ env.TAG }}
          jsfpdn/my_bin:latest
          ghcr.io/jsfpdn/my_bin:${{ env.TAG }}
          ghcr.io/jsfpdn/my_bin:latest

